import datetime
from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey, Boolean
from sqlalchemy.orm import relationship
from database import Base


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    full_name = Column(String, index=True)
    email = Column(String, unique=True, index=True)
    hashed_password = Column(String)
    is_2fa_enabled = Column(Boolean, default=False)
    otp_secret = Column(String, nullable=True)
    
    # Email Verification OTP fields
    otp = Column(String, nullable=True)
    otp_expiry = Column(DateTime, nullable=True)
    is_verified = Column(Boolean, default=False)


class Patient(Base):
    __tablename__ = "patients"

    id = Column(Integer, primary_key=True, index=True)
    full_name = Column(String, index=True)
    email = Column(String, unique=True, index=True)
    age = Column(Integer)
    gender = Column(String, nullable=True)
    phone = Column(String, nullable=True)
    address = Column(String, nullable=True)
    medical_history = Column(String, nullable=True) # Story of past conditions
    notes = Column(String, nullable=True) # Additional observations
    
    date_created = Column(DateTime, default=datetime.datetime.utcnow)

    # This patient can have many memory checks over time
    memory_checks = relationship("MemoryCheck", back_populates="patient_owner")

class MemoryCheck(Base):
    __tablename__ = "memory_checks"

    id = Column(Integer, primary_key=True, index=True)
    patient_id = Column(Integer, ForeignKey("patients.id"))
    date_performed = Column(DateTime, default=datetime.datetime.utcnow)
    
    # Raw scores from the frontend test
    memory_score = Column(Float)
    recall_score = Column(Float)
    attention_score = Column(Float)
    
    # Results generated by your backend logic/AI
    avg_score = Column(Float)
    result_status = Column(String)  # Detected / Not Detected
    result_stage = Column(String)   # Early / Normal
    ai_confidence = Column(Integer)

    # Link back to the patient
    patient_owner = relationship("Patient", back_populates="memory_checks")